from HitbotInterface import HitbotInterface
import time

print(1)
robot_id = 92
robot = HitbotInterface(robot_id)
robot.net_port_initial()
time.sleep(3)
print("initial successed")
ret = robot.is_connect()
robot.check_joint(1, False)
robot.check_joint(2, False)
robot.check_joint(3, False)
robot.check_joint(4, False)
ret = robot.initial(1, 210)
ret3 = robot.set_digital_out(1, 1)
time.sleep(1)
robot.set_digital_out(1, 0)
time.sleep(1)
robot.set_digital_out(2, 1)
time.sleep(1)
robot.set_digital_out(2, 0)
time.sleep(1)
robot.set_digital_out(3, 1)
time.sleep(1)
robot.set_digital_out(3, 0)
time.sleep(1)
robot.set_digital_out(4, 1)
time.sleep(1)
robot.set_digital_out(4, 0)
time.sleep(1)
robot.set_digital_out(5, 1)
time.sleep(1)
robot.set_digital_out(5, 0)
time.sleep(1)
robot.set_digital_out(6, 1)
time.sleep(1)
robot.set_digital_out(6, 0)
time.sleep(1)
robot.set_digital_out(7, 1)
time.sleep(1)
robot.set_digital_out(7, 0)
time.sleep(1)
robot.set_digital_out(8, 1)
time.sleep(1)
robot.set_digital_out(8, 0)
time.sleep(1)
robot.set_digital_out(9, 1)
time.sleep(1)
robot.set_digital_out(9, 0)
time.sleep(1)
robot.set_digital_out(10, 1)
time.sleep(1)
robot.set_digital_out(10, 0)
time.sleep(1)
robot.set_digital_out(11, 1)
time.sleep(1)
robot.set_digital_out(11, 0)
time.sleep(1)
robot.set_digital_out(0, 1)
time.sleep(1)
robot.set_digital_out(0, 0)
time.sleep(1)
robot.set_digital_out(12, 1)
time.sleep(1)
robot.set_digital_out(12, 0)
time.sleep(1)
robot.set_digital_out(13, 1)
time.sleep(1)
robot.set_digital_out(13, 0)
time.sleep(1)
robot.set_digital_out(14, 1)
time.sleep(1)
robot.set_digital_out(14, 0)
time.sleep(1)
robot.set_digital_out(15, 1)
time.sleep(1)
robot.set_digital_out(15, 0)
time.sleep(1)
robot.set_digital_out(16, 1)
time.sleep(1)
robot.set_digital_out(16, 0)
time.sleep(1)
robot.set_digital_out(17, 1)
time.sleep(1)
robot.set_digital_out(17, 0)
time.sleep(1)
robot.set_digital_out(18, 1)
time.sleep(1)
robot.set_digital_out(18, 0)
time.sleep(1)
robot.set_digital_out(19, 1)
time.sleep(1)
robot.set_digital_out(19, 0)
time.sleep(1)
robot.set_allow_distance_at_target_position(0.1, 0.1, 0.1, 0.1)
ret4 = robot.is_robot_goto_target()
if ret4 == 1:
    print("robot is_robot_goto_target successful")
else:
    print("robot is_robot_goto_target fail")
if ret3 == 1:
    print("robot set_digital_out successful")
else:
    print("robot set_digital_out fail")
ret2 = robot.get_hard_emergency_stop_state()
if ret2 == 1:
    print("robot get_hard_emergency_stop_state successful")
else:
    print("robot get_hard_emergency_stop_state fail")
if ret == 1:
    print("robot initial successful")
else:
    print("robot initial failed")

if ret == 1:
    print("robot initial successful")
    robot.unlock_position()

    # A->D
    robot.new_movej_xyz_lr(23.77,63.74,-34,-10,70,0,1)
    robot.wait_stop()
    robot.new_movej_xyz_lr(68.25, -3.2, -34, -82.8, 70, 0.4,1)
    robot.new_movej_xyz_lr(121.8,-372,-34,-156,120,0.4,1)
    robot.new_movej_xyz_lr(-39.34,-374,-5,-159.75,120,0,-1)
    robot.wait_stop()
    #D->A
    robot.new_movej_xyz_lr(-39.34,-374,-5,-159.75,120,0.4,-1)
    robot.new_movej_xyz_lr(121.8,-372,-34,-156,120,0.4,1)
    robot.new_movej_xyz_lr(68.25, -3.2, -34, -82.8, 120,0,1)
    robot.wait_stop()
    robot.new_movej_xyz_lr(23.77,63.74,-34,-10,70,0,1)
    robot.wait_stop()

