joint_limits:
  joint1:
    has_position_limits: true
    min_position: -0.3
    max_position: 0.3
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.14     # rad/s²
  joint2:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.14     # rad/s²
  joint3:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 3.14     # rad/s²
  joint4:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true 
    max_acceleration: 3.14     # rad/s²

