# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 0.0
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.1
  
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scara_arm_controller

  scara_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    excution_duration_monitoring: 10
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
#      - joint5
    action_ns: follow_joint_trajectory
    default: true
