# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    scara_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      allow_partial_joints_goal: true


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

scara_arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
#      - joint5
#      - joint6
#      - joint7
    command_interfaces:
      - position
        #- velocity
    state_interfaces:
      - position
        #- velocity
