/scara_motor_driver_node:
  ros__parameters:

    joint_count: 5
    joints:  ['joint1', 'joint2', 'joint3', 'joint4','joint5']
    motors:  ['J1',     'J2',     'J3',     'J4',     'J5']
    offsets: [0.0,      -1.28,    -2.71,    0.0,      0.0]
    ratios:  [-107.0,   1.0,      1.0,      20.0,     20.0]
    
    #joints:  ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6', 'joint7']
    #motors:  ['J1',     'J2',     'J3',     'J4',     'J5',     'J6',     'J7']
    #offsets: [0.0,      -1.28,    -2.71,    0.0,      0.0,      0.0,      0.0]
    #ratios:  [-107.0,   1.0,      1.0,      20.0,     20.0,     20.0,     108.0]
